### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'buf'

### ISSUE THREAD

**Issue by lakshprakash** [Bibyutatsu/proGENTRL#3]
torch.cuda.is_available() ---> True

But still its failing with following error. Kindly help

Cannot Load the Models: Enc Model not Found 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-f92eee7878d3> in <module>
      5                          train_loader,
      6                          latent_descr,
----> 7                          feature_descr, load_model='./model/')

~\Desktop\proGENTRL-master\proGENTRL-master\progentrl\gen_vaelp.py in __init__(self, enc, dec, train_loader, latent_descr, feature_descr, tt_int, tt_type, beta, gamma, load_model)
     53             self = load(self, load_model)
     54 
---> 55         self.buf = None
     56 
     57     def get_elbo(self, x, y):

AttributeError: 'NoneType' object has no attribute 'buf'

**Comment by Bibyutatsu** [comment]
Hi,
There is an argument `load_model` which loads an existing model. Just remove it and it will work.

**Comment by Bibyutatsu** [comment]
Hi @lakshprakash ,
I hope it solved your problem so I am closing this issue. Feel free to reopen it if you face any problem.
